#!/bin/bash

# Vars.
AUTHOR=adpc
NAME=nginx/php
TAG=1.0
PORT_80=8080
PORT_443=4430
USER=${USER}
HOME_PATH=${HOME}
PWD_PATH=$(pwd)
READ_LINK=$(readlink -f $0)
DIR_NAME=$(dirname ${READ_LINK})
ROOT_PATH=${DIR_NAME}
LOG_PATH=${ROOT_PATH}/logs
SITE_PATH=${ROOT_PATH}/site
CONFIG_PATH=${ROOT_PATH}/config

# Run docker container.

# SERVER_ADDR='<SERVER_ADDR>'

# DOCKER_NAME='<DOCKER_NAME>'

# VIRTUAL_TYPE=<VIRTUAL_TYPE>
# VIRTUAL_HOST='<VIRTUAL_HOST>'
# VIRTUAL_VOLUME='<VIRTUAL_HOST>'
# VIRTUAL_PORT_80='<VIRTUAL_PORT_80>'
# VIRTUAL_PORT_443='<VIRTUAL_PORT_443>'

# Use in Development.
# docker run --name ${DOCKER_NAME} -it --rm -e SERVER_ADDR=${SERVER_ADDR} -e VIRTUAL_HOST=${VIRTUAL_HOST} -e VIRTUAL_TYPE=${VIRTUAL_TYPE} -p ${VIRTUAL_PORT_80}:80 -p ${VIRTUAL_PORT_443}:443 -v ${VIRTUAL_VOLUME}:/var/www/html ${AUTHOR}/${NAME}:${TAG}

# Use in Production.
# docker run --name ${DOCKER_NAME} -d -it --rm -e SERVER_ADDR=${SERVER_ADDR} -e VIRTUAL_HOST=${VIRTUAL_HOST} -e VIRTUAL_TYPE=${VIRTUAL_TYPE} -p ${VIRTUAL_PORT_80}:80 -p ${VIRTUAL_PORT_443}:443 -v ${VIRTUAL_VOLUME}:/var/www/html ${AUTHOR}/${NAME}:${TAG}

if [ $# -lt 6 ]
then

  echo 'ERROR: No argument supplied';
  echo 'SYNTAX: '${0}' <DOCKER_NAME> <SERVER_ADDR> <VIRTUAL_TYPE> <VIRTUAL_HOST> <VIRTUAL_VOLUME> <VIRTUAL_PORT_80> <VIRTUAL_PORT_443>';

else

  DOCKER_NAME=${1}
  SERVER_ADDR=${2}

  # SITE

  VIRTUAL_TYPE=${3}
  VIRTUAL_HOST=${4}
  VIRTUAL_VOLUME=${SITE_PATH}'/'${5}
  VIRTUAL_PORT_80=${6}
  VIRTUAL_PORT_443=${7}

  docker run --name ${DOCKER_NAME} -d -it --rm -e SERVER_ADDR=${SERVER_ADDR} -e VIRTUAL_HOST=${VIRTUAL_HOST} -e VIRTUAL_TYPE=${VIRTUAL_TYPE} -p ${VIRTUAL_PORT_80}:80 -p ${VIRTUAL_PORT_443}:443 -v ${VIRTUAL_VOLUME}:/var/www/html ${AUTHOR}/${NAME}:${TAG}

fi
